# For Register
POST http://localhost:3000/auth/signup
Content-Type: application/json

{
    "email": "ali@mail.com",
    "password": "123"
}

###

POST http://localhost:3000/auth/signin
Content-Type: application/json

{
    "email": "ali@mail.com",
    "password": "123"
}
